import './globals.css';
if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap")
};
import "../style/index.scss";
import AppProvider from '@/contextApi/AppProvider';
import ReduxProvider from '@/redux/provider';
import { ToastContainer } from 'react-toastify';
import UseMousePointer from '@/utils/MouseCursorUtilis';
import { DirectionProvider } from '@/hooks/useDirection';

export const metadata = {
  title: 'SnK Music  - Music Bands and Musicians',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.ico" />
        </head>

        <body suppressHydrationWarning={true}>
          {/* Use the UseMousePointer component */}
          <UseMousePointer />
          <ReduxProvider>
            <AppProvider>
              <DirectionProvider>
              {children}
              </DirectionProvider>
            </AppProvider>
            <ToastContainer
              position="top-left"
              autoClose={1000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ReduxProvider>
        </body>
      </html>
    </>
  )
}
